### ISSUE TITLE
Recipient Variables to batch emails?

### ISSUE THREAD

**Issue by kkazene** [bojand/mailgun-js#101]
I'm trying to send batch emails that would make use of variables, such as %recipient.firstname% etc, as described [here](https://documentation.mailgun.com/user_manual.html#batch-sending).

However, I can't get it to work, since apparently this isn't supported anywhere yet. Is there any chance this could be implemented?

**Comment by bojand** [comment]
It should work fine like so...

```
var params = {
  to: ['Person1 <email1@gmail.com>'],
  bcc: ['Person2 <email2@gmail.com>'],
  from: 'Me <me@outlook.com>',
  subject: 'Hey, %recipient.first%',
  text: 'testing message for mailgun',
  html: 'HTML version of body'
};

params['recipient-variables'] = {
  "email1@gmail.com": {
    first: 'Person1Name'
  },
  "email2@gmail.com": {
    first:"Person2Name"
  }
};

mailgun.messages().send(params, function(err, body) {
  if (err) console.dir(err.message);
  console.dir(body);
});
```

**Comment by NTruchaud** [comment]
Hi,
I can't figure out the way to send thousands of mails at once with batch sending. I've tried with the API from mailgun documentation, but I don't see how to prepare my batch sending, how to split the values, how to consctruct my JSON the right way...
If someone had an accurate example, it would be great, because I can't find anything on the net.

Thank you guys,

**Comment by bojand** [comment]
Hello there is complete documentation [here](https://documentation.mailgun.com/user_manual.html#batch-sending). 
Sample code:

```js
recipientVars = {
  'bob@companyx.com': {
    first: 'Bob',
    id: 1
  },
  'alice@companyy.com': {
    first: 'Alice',
    id: 2
  }
};

var data = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: ['bob@companyx.com', 'alice@companyy.com'],
  subject: 'Hey, %recipient.first%',
  'recipient-variables': recipientVars,
  text: 'If you wish to unsubscribe, click http://mailgun/unsubscribe/%recipient.id%',
};

mailgun.messages().send(data, function (error, body) {
  console.log(body);
});
```

**Comment by intellix** [comment]
Nice that recipient variables use percentages and regular variables require mustache/handlebar variables.
