### ISSUE TITLE
Attachment does not support Content-Disposition / Content-ID header

### ISSUE THREAD

**Issue by elhigu** [bojand/mailgun-js#103]
Mailgun API supports setting Content-ID and Content-Disposition: inline by passing inline= parameter to rest api.

https://documentation.mailgun.com/user_manual.html#sending-via-api

Without this feature it is not possible to create html mails with images embedded to email.

**Comment by bojand** [comment]
Can you elaborate please with some sample code and behaviour?

var file = path.join(__dirname, 'mailgun_logo.png');

```js
var params = {
  to: 'test@test.com',
  from: 'Me <me@test.com>',
  subject: 'Hello testing mailgun',
  html: '<html>Inline image here: <img src="cid:mailgun_logo.jpg"></html>',
  inline: file
};

mailgun.messages().send(params).then(function (body) {
  console.log(body);
}).catch(function(err) {
  console.error(err);
});
```

Sends fine with the inline image. Part of message source:

```
--d496bc37ee1e48138d5d142370200a3e
Content-Id: <mailgun_logo.png>
Content-Disposition: inline; filename="mailgun_logo.png"
Content-Type: image/png; name="mailgun_logo.png"
Mime-Version: 1.0
Content-Transfer-Encoding: base64
```

**Comment by elhigu** [comment]
Hi, thanks for the example. 

Looks like that I just missed the part of documentation where the usage of inline attachments were mentioned. I was looking for it from `Attachment` class to be able to set Content-ID and filename separately. 

Anyways this solution is enough for me to be able to continue.
