### ISSUE TITLE
generic-requests aren't promises

### ISSUE THREAD

**Issue by saiichihashimoto** [bojand/mailgun-js#106]
1) mailgun-js v0.7.12

2) node v6.2.2 on OSX

3) All the native api methods can either use callbacks [or promises](https://github.com/bojand/mailgun-js#promises). However the [generic requests](https://github.com/bojand/mailgun-js#generic-requests) don't return as promises.

**Comment by bojand** [comment]
Hello, can you please provide some sample source code. The following sample source code works fine for me:

```js
var path = '/' + domain + '/stats'
mailgun.get(path, { event: ['sent', 'delivered'] }).then(body => {
  console.log(body)
}).catch(err => {
  console.log(err)
});
```

**Comment by saiichihashimoto** [comment]
This wasn't working for me:

```
mailgun.get('/address/validate', { address: 'dummyemail@nowhere.not' }).then(body => {
  console.log(body)
}).catch(err => {
  console.log(err)
});
```

But this was:

```
mailgun.get('/address/validate', { address: 'dummyemail@nowhere.not' }, (err, body) => {
  console.log(err);
  console.log(body);
});
```

**Comment by bojand** [comment]
Hmm are you using your public api key as the [documentation](https://documentation.mailgun.com/api-email-validation.html) states? It works for me:

```js
var mg = new mailgun.Mailgun({apiKey: public_api_key, domain: domain})
mg.get('/address/validate', { address: 'testmg@gmail.com' }).then(body => {
  console.log(body);
}).catch(err => {
  console.log(err);
});
```
