### ISSUE TITLE
get a 401 Forbidded even for valid parameters

### ISSUE THREAD

**Issue by saraf** [bojand/mailgun-js#107]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
latest version installed with npm install --save mailgun-js
"mailgun-js": "^0.7.12",

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
node-6.2.2 on Ubuntu 14.04

3) Sample source code or steps to reproduce

Following the tutorial on http://blog.mailgun.com/how-to-send-transactional-emails-in-a-nodejs-app-using-the-mailgun-api/

I am using mailgun-js API from node.js.

I have the following code -

```
function sendEmail(writeString, shortString, cb) {
var api_key = "key-****f7fd5";
var domain = "sandbox6756f406403b4c78bdf70c8df0*.mailgun.org";
var mailgun = new Mailgun({api_key: api_key, domain: domain});
var data = {
//Specify email data
//The email to contact
from: "postmaster@sandbox6756f406403b4c78bdf70c8df0665570.mailgun.org",
to: "aal@gmail.com",
//Subject and text data
subject: 'Badve welding report',
html: writeString
};

//Invokes the method to send emails given the above data with the helper library
mailgun.messages().send(data, function (err, body) {
//If there is an error, render the error page
if (err) {
console.log("got an error trying to send email: ", err);
cb(null, shortString)
}
else {
console.log(body);
cb(null, shortString)
}
});
},
```

I get the following 401 - forbidden error:
got an error trying to send email:
```
 { Error: Forbidden
at IncomingMessage.<anonymous> (/home/aal/sandbox/lineview/badve/bdvApp/node_modules/mailgun-js/lib/request.js:309:15)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:934:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: 401 }
```

I have verified that the api key and the domain name is correct and that the recipient is authorized for the sandbox domain.

Using CURL from the command line with the same parameters works.

Any help would be much appreciated.

**Comment by saraf** [comment]
My bad. There was a typo in my code. I was using api_key instead of apiKey.
Sorry for the bother.

**Comment by MohamedEllouze** [comment]
I have the same problem here
