### ISSUE TITLE
Cannot BCC 

### ISSUE THREAD

**Issue by greggmojica** [bojand/mailgun-js#110]
Cannot BCC with MailComposer?

**Comment by bojand** [comment]
Can you post details and sample code that reproduces the issue please (like the issue template suggests).

**Comment by kdekooter** [comment]
Please note that the `to` field is required and should contain all recipients (to/cc/bcc). Any recipient in the `bcc` field will receive the message as BCC. See https://documentation.mailgun.com/api-sending.html#sending
