### ISSUE TITLE
setting message-id in headers

### ISSUE THREAD

**Issue by harmonicradius** [bojand/mailgun-js#111]
I'm interested in setting headers of emails that are generated by events on the server so that things can get threaded at the recipient

1) What version of the module is the issue happening on? Does the issue happen on latest version?
    "mailgun-js": "0.7.11",

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
   node 6
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
  setting headers as 
"h:Message-Id" : "inboundaddress+hash@mydomain.com"
or 
"h:Reply-To" : "inboundaddress+hash@mydomain.com"
 seems to.
  

4) Sample source code or steps to reproduce

Using the npm package: 
const Mailgun = require('mailgun-js');

const mailgun = new Mailgun({
  apiKey: process.env.MAILGUN_API_KEY,
  domain: process.env.MAILGUN_DOMAIN,
});

      mailgun.messages().send(
        _.assign({ }, {
          from: process.env.MAILGUN_EMAIL_FROM,
          subject,
          to,
          html: template,
            'h:Message-ID':  `${messageID}@website.ca`,
       //   'h:In-Reply-To': `${messageID}@website.ca`,
        }),
        (error, response) => {

          // An error has occurred, reject with the error
          if (error) {
            return reject(error);
          }

          // Sending the email was successful, return the response
          return resolve(response);
        }
      );

^ Of course, this is happening inside a promise type function, so the returns / reject work as expected.

If this is not correct, how can I apply headers correctly?

Thanks.

**Comment by bojand** [comment]
as the [docs](https://documentation.mailgun.com/api-sending.html#sending) state you can just add `h:*` as body param and it will be added as a custom header for the message. Mailgun-js also supports promises so you can just return that.

```js
const mailgun = require('mailgun-js')({
  apiKey: MY_MAILGUN_APIKEY,
  domain: MY_MAILGUN_DOMAIN
});

const from = 'test@test.com';
const to = 'me@gmail.com';
const subject = 'test subject';
const template = '<h2>TEST EMAIL</h2>';
const messageID = 'msg123';

function sendEmail() {
  return mailgun.messages().send({
    from,
    to,
    subject,
    html: template,
    'h:Message-ID':  `${messageID}@website.ca`,
    'h:In-Reply-To': `${messageID}@website.ca`,
  });
}

sendEmail()
  .then(response => console.log(response))
  .catch(err => console.error(err));
```

**Comment by harmonicradius** [comment]
Thanks for looking into this.. I am still having some trouble though: 

h:Message-ID headers seem to work fine. They show up in the mailgun logs as expected, but when I try to apply 'h:In-Reply-To' (or h:References) headers, they don't appear in the mailgun logs, and my messages don't get threaded. What's weirder is that if I view the original message source, I can read the headers there. Here's the top of the actual email that arrives. (I have replaced the identifying marks with WEBSITE.CA and redacted identifying material).


Received: from YTOPR01MB0297.CANPRD01.PROD.OUTLOOK.COM (10.166.151.139) by
 YQBPR01MB0291.CANPRD01.PROD.OUTLOOK.COM (10.169.142.15) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.707.6 via Mailbox Transport; Fri, 11 Nov 2016 19:03:19 +0000
Received: from YQXPR01CA0072.CANPRD01.PROD.OUTLOOK.COM (10.165.103.40) by
 YTOPR01MB0297.CANPRD01.PROD.OUTLOOK.COM (10.166.151.139) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.721.10; Fri, 11 Nov 2016 19:03:18 +0000
Received: from TO1CAN01FT004.eop-CAN01.prod.protection.outlook.com
 (2a01:111:f400:7e5d::202) by YQXPR01CA0072.outlook.office365.com
 (2a01:111:e400:5b9f::40) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.721.10 via
 Frontend Transport; Fri, 11 Nov 2016 19:03:18 +0000
Authentication-Results: spf=pass (sender IP is xxx.xxx.xxx.xxx)
 smtp.mailfrom=WEBSITE.CA; live.com; dkim=pass
 (signature was verified)
 header.d=WEBSITE.CA;live.com; dmarc=bestguesspass
 action=none header.from=WEBSITE.CA;
Received-SPF: Pass (protection.outlook.com: domain of
 WEBSITE.CA designates xxx.xx.xx.xxx as permitted
 sender) receiver=protection.outlook.com; client-ip=209.61.151.224; helo=
 rs224.mailgun.us;
Received: from BLU004-MC1F30.hotmail.com (10.152.122.59) by
 TO1CAN01FT004.mail.protection.outlook.com (10.152.122.115) with Microsoft
 SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.707.3 via Frontend
 Transport; Fri, 11 Nov 2016 19:03:17 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:;UpperCasedChecksum:;SizeAsReceived:2016;Count:19
Received: from rs224.mailgun.us ([209.61.151.224]) by BLU004-MC1F30.hotmail.com over TLS secured channel with Microsoft SMTPSVC(7.5.7601.23143);
	 Fri, 11 Nov 2016 11:03:15 -0800
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed;
 d=WEBSITE.ca; q=dns/txt; s=mailo;
 t=1478890989; h=Content-Transfer-Encoding: Mime-Version: Content-Type:
 Subject: From: To: In-Reply-To: References: Message-Id: Date: Sender;
 bh=ObXE+ixop4UIx94DLRynX9PEZ7sioHDQg0TK3CF4iuU=; b=lIrNhPx0h3cSvry+bYRwyQbIm64hVolSa2s5685DKlCeOIqp76FJvIXCkT04Tl6oKqZ3uDbI
 4ezH4Wl17DN6LOGnq8JP5fKwL+VF43p5M0426Q5xfqhhrXaJZbQ87T5WvzqeuRgXX6QiBpO4
 V3iI39GfNKern2IVokigEDBH2Fo=
DomainKey-Signature: a=rsa-sha1; c=nofws;
 d=WEBSITE.CA; s=mailo; q=dns; h=Sender:
 Date: Message-Id: References: In-Reply-To: To: From: Subject:
 Content-Type: Mime-Version: Content-Transfer-Encoding;
 b=MBVV96hpq2uKJOHyi0fTa0p2ypoAI/d+fAtO871SRPTdY9WEuphraibNQA8/XK96ZW6wtz
 S5mlTpKo1bnuT86tR0nGvJ2mfOVU6VwqkRBoUzeeNhCdGQaBtonfRSK4TLnVdoXcckRG9kEJ
 JlUfIDZtZZgrJLmq6hFx1Vo+krQmc=
Sender: noreply@WEBSITE.CA
Date: Fri, 11 Nov 2016 19:03:09 +0000
X-Mailgun-Sending-Ip: 209.61.151.224
X-Mailgun-Sid: -------------redacted---------=
Received: by luna.mailgun.net with HTTP; Fri, 11 Nov 2016 19:03:09 +0000
Message-Id: <20161111190309.7341.10408.ECE9B90E@WEBSITE.CA>
References: <MessageID@WEBSITE.CA>
In-Reply-To: <MessageID@WEBSITE.CA>
To: user@email.com
From: noreply@WEBSITE.CA
Subject: correct subject, 

.....

How can I get these headers to stick? Is it possible that mailgun will only let you reference message-IDs that they themselves have created?
