### ISSUE TITLE
Check for pipe function instead of Readable instance

### ISSUE THREAD

**Issue by Fluidbyte** [bojand/mailgun-js#115]
The library worked great for us, and the docs do a good job of calling this out (`an instance of Readable which means it is a readable stream`), but the need for an attachment readStream to be an instance of `streams.Readable` caused issues when developing.

We attempted to use [s3-streams#ReadStream](https://www.npmjs.com/package/s3-streams#read-streams) which returns a legitimate read stream, but doesn't return an instance of `Readable`:

```javascript
const S3S = require('s3-streams')
const S3 = require('aws-sdk').S3
const mailgun = require('mailgun-js')

// ...

const attachStream = S3S.ReadStream(new S3(), {
    Bucket: 'my-bucket',
    Key: 'my-key',
})

console.log(attachStream instanceof require('stream').Readable) // -> false

attachment = new mailgun.Attachment({
  data: attachStream, // <- no-go
  filename: attachName,
  knownLength: attachContentLength,
  contentType: attachContentType
})

// ...
```

My suggestion, unless there's a solid reason which I'm missing, would be to check the stream/data for a `pipe` method.

It took us trying 3 other libraries to find one that worked [S3#ClientDownloadStream](https://www.npmjs.com/package/s3#clientdownloadstreams3params)

**Comment by bojand** [comment]
Thanks. I can understand this is legitimate issue. We could use something like [is-stream](https://github.com/sindresorhus/is-stream) to check the object. Will try to have a fix soon.
