### ISSUE TITLE
mailgun.messages().send gives error 404 Not found.

### ISSUE THREAD

**Issue by ShashiBadhuk** [bojand/mailgun-js#118]
```
{ Error: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at IncomingMessage.<anonymous> (/Users/shashi/Workspace/mailgundemo/node_modules/mailgun-js/lib/request.js:309:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: 404 }

```

**Comment by bojand** [comment]
Please provide sample source code to reproduce the issue.

**Comment by ShashiBadhuk** [comment]
Sample Code
```
var api_key = 'api:APIKEY';
var domain = 'https://api.mailgun.net/v3/DOMAINNAME/messages';
var Mailgun = require('mailgun-js');

//We pass the api_key and domain to the wrapper, or it won't be able to identify + send emails
    var mailgun = new Mailgun({apiKey: api_key, domain: domain});

    var data = {
    //Specify email data
      from: "contact@shashibadhuk.com",
    //The email to contact
      to: "shashi.badhuk@affle.com",
    //Subject and text data
      subject: 'Hello from Mailgun',
      html: 'Hello,There I am using mailgun'
    }

    //Invokes the method to send emails given the above data with the helper library
    mailgun.messages().send(data, function (err, body) {
        //If there is an error, render the error page
        if (err) {
            //res.render('error', { error : err});
            console.log("got an error: ", err);
        }
        //Else we can greet    and leave
        else {
            //Here "submitted.jade" is the view file for this landing page
            //We pass the variable "email" from the url parameter in an object rendered by Jade
           // res.render('submitted', { email : req.params.mail });
            console.log(body);
        }
    });
```

**Comment by ShashiBadhuk** [comment]
Sometimes It gives 301 Moved Permanently error too. is there any issue with my system ports??

**Comment by bojand** [comment]
1) What version of the module is the issue happening on? Does the issue happen on latest version?

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)

3) Does the action work when you manually perform request against mailgun using curl (or other means)?

**Comment by jacobboon** [comment]
I ran into this issue too. I fixed it by replacing

`var domain = 'https://api.mailgun.net/v3/DOMAINNAME/messages';`

with

`var domain = 'DOMAINNAME';`

mailgun-js will append and prepend everything else. :)

**Comment by yogendra85** [comment]
i found same issue bt not resolve

**Comment by yogendra85** [comment]
k

**Comment by Tymek** [comment]
sidenote: if you are using EU servers, you should also define `host`. I spend too much time debugging that. RTFM 😂

**Comment by Tymek** [comment]
sidenote, might be helpful: if you are using **EU servers**, you should also define `host`. I spend too much time debugging that. RTFM 😂

**Comment by wuliaopage** [comment]
> sidenote, might be helpful: if you are using **EU servers**, you should also define `host`. I spend too much time debugging that. RTFM 😂

Thanks so much for hint, and just to remind others.
change the original code to the following one.
const mailgun = require('mailgun-js')({apiKey: apiKey, domain: domain,host:"api.eu.mailgun.net"})

**Comment by LeonBuchner** [comment]
Thank you very much!

**Comment by null9beta** [comment]
@Tymek still it's mid-2020 already, that hint must have saved me hours of debugging. I still wonder why it's not mentioned in the docs

**Comment by Tymek** [comment]
@null9beta here [npmjs.com/package/mailgun-js#options](https://www.npmjs.com/package/mailgun-js#options). That's why I remarked RTFM :wink: 

Maybe this should be more prominent. If you think so, please PR such a change.

![Screenshot from 2020-07-01 09-55-41](https://user-images.githubusercontent.com/2625371/86218490-238f7180-bb81-11ea-8bb5-56c3ad70b814.png)
