### ISSUE TITLE
can you pls clear my doubts. ?

### ISSUE THREAD

**Issue by suriyaJaay** [bojand/mailgun-js#119]
i just got following issues from my cmd terminal

**{ message: 'Mailing list NAME@MAILINGLIST.COM not found' }**

**got an error:  [Error: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients
 in domain settings.]**

app.js
------

i just changed the following things 

var api_key = 'MAILGUN-API-KEY';
var domain = 'YOUR-DOMAIN.com';
var from_who = 'your@email.com';

**with below**

var api_key = 'key- here i put my own api key';
**var domain = 'sandbox43243243242342342.mailgun.org';  ---> is this correct?
var from_who = 'MyName@MyCompanyName.in';**

could you pls tell me what is actually domain name and where can i get from mailgun dashboard.?

from my mailgun account i found my api key and email validation key from settings

thank you

**Comment by bojand** [comment]
yes domain name would be like that... something like `'sandbox123456.mailgun.org'`
