### ISSUE TITLE
How do I send multiple "to" with sendMime?

### ISSUE THREAD

**Issue by dmolineuxcb** [bojand/mailgun-js#122]
Hi there, I am getting an error when I try to send `to` as an array to `sendMime()` is there another way to send multiple to addresses?
```
Invalid parameter type. to must be of type: string.\n    at constructor.(anonymous function) [as sendMime]
```
Thank you,
Doug

**Comment by dmolineuxcb** [comment]
Actually I read on mailgun api docs, that it could be a comma separated list, I am going to try this.

**Comment by dmolineuxcb** [comment]
commas separated lists work with "To", however "CC"ing doesn't seem to work, when the same object is sent to sendMime(), is this a known issue? Or am I doing something wrong?

**Comment by bojand** [comment]
Can you please try the latest version 0.7.15?

**Comment by dmolineuxcb** [comment]
wow it suddenly seems to be working? lol thank you, 👍
