### ISSUE TITLE
Mailgun Event Polling

### ISSUE THREAD

**Issue by petrogad** [bojand/mailgun-js#125]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.7.12

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
6.8.1 OSX

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
Works fine

4) Sample Code:
```JS
const getMailgunSeconds = function (time) {
	return (new Date(time).getTime()/1000).toString();
};

const date = getMailgunSeconds('January 18, 2017');
const opts = {begin: begin, ascending: 'true', limit: 5, event: 'delivered'};
mailgun.events().get(opts)
  .then((mailgunMetrisc) => {
        console.log(mailgunMetrics.paging.next);
   });
```

I'm trying to poll events to get all the results back based on [event polling](https://documentation.mailgun.com/api-events.html#event-polling). The first request works just fine (shown above), however I'm trying to understand how to make requests to the paging elements that are provided in the docs.

An array key of `paging.next` comes back, but I don't know where / how to make the requesting URL.

Thank you kindly!

**Comment by bojand** [comment]
Once you get the initial response you just use iteratively `mailgun.get()` to request the full URL of the next page until done. You should follow the instructions in the event polling [event polling](https://documentation.mailgun.com/api-events.html#event-polling) to iterate through all the requests. Note to do it in proper async way, so using something like [p-whilst](https://github.com/sindresorhus/p-whilst) may be helpful.

**Comment by ewagoner** [comment]
Breadcrumbs for future Googlers:

`mailgun.get()` automatically includes the `https://api.mailgun.net/v3` part of the url, so when you pass your `paging.next` link to it, you'll need to strip that off first or else it will silently fail.

**Comment by binarymist** [comment]
Thanks @ewagoner, that was the answer I'd been looking for for hours!
