### ISSUE TITLE
Dynamic API hostname required in get message URL

### ISSUE THREAD

**Issue by hubsmoke** [bojand/mailgun-js#128]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
Latest
2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
v6.3.0 Mac OS X
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
No
4) Sample source code or steps to reproduce

My mailgun.js is configured to use a host 'api.mailgun.net'

When I make a call to the `/events` endpoint I get a list of messages that have URLs that include a subdomain 'XX.api.mailgun.net'

from the /events call:
```
...,
{
      "tags": [], 
      "timestamp": 1482969601.031548, 
      "storage": {
        "url": "https://si.api.mailgun.net/v3/domains/example.com/messages/key", 
        "key": "key"
      }, 
      "envelope": {
        "sender": "example@example.com", 
        "transport": "smtp", 
        "targets": "example@example.com"
      }, 
...
```

You see, that "si" is prepended to the host. The problem is that I can't simply change the host, because other messages are on the "se.api.mailgun.net" and "sw.api.mailgun.net", etc.

It seems like this api.mailgun.net subdomain should actually be dynamic.

The end result is I get a 404 when attempting to GET the messages from the event results. When I update the host to include the subdomain, I get the message as expected. The problem is that these subdomains don't seem to be predictable and change over time

Has anyone run into this before? I'm investigating how to update the mailgun.js source with minimal impact

**Comment by bojand** [comment]
Hello, you can create a new instance of `Mailgun` object and specify a `host` parameter `'si.api.mailgun.net'` and it should work against that domain.

```
const siMg = new Mailgun({
  host: 'si.api.mailgun.net',
  domain: 'example.com',
  apiKey: 'key-XXXXXXXXXXXXXXXXXXXXXXX'
})
```

**Comment by hubsmoke** [comment]
Sure, that's what I ended up doing. It seems weird to have to create a new
instance for each domain, but the new instance doesn't really cost anything
so it's probably the best solution.
