### ISSUE TITLE
Package.json "engines" criteria is too strict

### ISSUE THREAD

**Issue by newyorkpizza** [bojand/mailgun-js#131]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
Yes

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
Node v4.x.x

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
Not applicable

4) Sample source code or steps to reproduce

We are running Node v4.x.x and using `yarn` to install the `mailgun-js` package. Based on this project's package.json file, the yarn installation expectedly fails with 
```error mailgun-js@0.8.1: The engine "node" is incompatible with this module. Expected version ">=6.9".``` since the version of node that we use does not meet mailgun-js's package.json's `engine` requirement (https://github.com/bojand/mailgun-js/blob/master/package.json#L19). 

Our current workaround is to use `yarn --ignore-engines`. 

However, it appears that the `engine` requirement is too strict. The updated engine requirement was introduced in: https://github.com/bojand/mailgun-js/commit/79da7c7bff24a8b44b3223b306aa6d567a2248b0 which updates the dependency on `promisify-call` to v2. In `promisy-call`'s package.json, the required engine is `>=4.0`: https://github.com/bojand/promisify-call/blob/master/package.json.

Since Node v4 supports native promises, it looks like package.json could be changed to ```  "engines": {
    "node": ">=4.0"
  },``` which would ensure mailgun-js compatibility with older version of Node and would allow us to remove our workaround (i.e. of invoking yarn with `--ignore-engines`).

**Comment by bojand** [comment]
Hello, thanks for the thorough issue report. You're right, this is too restrictive and an oversight on my part when I was upgrading to `promisify-call`. Addressed and published as 0.9.1. Let me know if this doesn't work and we can reopen the issue if needed.

**Comment by newyorkpizza** [comment]
That did the trick. Thanks for the quick fix!
