### ISSUE TITLE
Error when trying to import 'mailgun-js'

### ISSUE THREAD

**Issue by protoEvangelion** [bojand/mailgun-js#132]
Is it possible to use `import` syntax instead of `require` when using this module?

Webpack is failing to compile when I use **import** syntax instead of **require**.

Thanks!

**Comment by jonathanphz** [comment]
You figured this out?

**Comment by protoEvangelion** [comment]
@jonathanphz I couldn't get it to work.  I ended up just doing `const Mailgun = require('mailgun-js')`.  Sorry for not explaining that when closing.
