### ISSUE TITLE
could you add a batch sending example in the docs?

### ISSUE THREAD

**Issue by mezod** [bojand/mailgun-js#134]
Hi!
Thanks for this great lib!

I was reading the docs and realized there's no example on how to use it for batch sending/recipient variables. I found a couple of issues here that gave me an idea of how to approach it but I'm still not 100% sure. 

1) I understand that I need to pass an array of emails to the "to".
2) I understand I need to build a json 

```
{
  "bob@example.com": {
      "first":"Bob", 
      "id":1
   }, 
  "alice@example.com": {
      "first":"Alice",
      "id": 2
   }
}
```
and pass it to 'recipient-variables' but that the lib will stringify it for me.

3) Use the %recipient.first% templating form fro mailgun in the subject/text.

Sorry, this post was kind of a learning process for me, but still, could you add a simple batch sending example with recipient variables in the docs? Might be useful!

Thanks again!

**Comment by mezod** [comment]
works, but still, an example would rock!

**Comment by kamilml** [comment]
here is the example https://github.com/bojand/mailgun-js/blob/master/test/mailgun.test.js#L43

and https://github.com/bojand/mailgun-js/blob/master/test/fixture.json#L8 has the data in `"message_recipient_vars"`

**Comment by mezod** [comment]
The first link is the test for it and the second, I'm not sure to be honest. Thanks for the links, though. I already made it work thanks to the code in other issues. I just suggested to add an example in the readme since it might be a very common need. Feel free to close this issue though!
Thanks!
