### ISSUE TITLE
How to compile or build to deploy?

### ISSUE THREAD

**Issue by kamilml** [bojand/mailgun-js#135]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
https://puu.sh/vfq4Z/f0d0df382a.png
https://puu.sh/vfq4Z/f0d0df382a.png

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
node v6.10.0

4) Sample source code or steps to reproduce
https://github.com/kamilml/mail

---

I can send mail to easy with `mailgun.messages().send(data, function (error, body) {});` all is fine, but when I've tried to compile a build.js with webpack I get some errors.
I want to get a build.js file to production. Please help me. How I can do it?

---

Another question: what is the difference to https://github.com/mailgun/mailgun-js ?

**Comment by bojand** [comment]
Hmm this `mailgun-js` is intended to be used from within a Node.js environment... I am not sure if this module can be used from within the browser. I have never tested it, but some of its features (such as stream and file attachments) would require a Node.js environment. Plus you would need to use a proxy to get around the CORS issue and additionally you also need your private api key on the browser side and I am not sure how that could be accomplished securely.

https://github.com/mailgun/mailgun-js

Seems like that's an official Node.js / JavaScript client... I actually didn't know this exists. Must be relatively new as it didn't exist when I started this module. From a quick look seems the differences are in the API itself, also I think this module supports attachments, where that one does not. Although that one can be used from within the browser.
