### ISSUE TITLE
Example for Curl Command

### ISSUE THREAD

**Issue by geosh03** [bojand/mailgun-js#136]
I am trying to execute the following curl command using mailgun-js:

curl -sv --user 'api:key-{key}' -G https://api.mailgun.net/v3/mg.casctesla.com/events --data-urlencode recipient=testman1@mg.casctesla.com --data-urlencode limit=1

I want to look at the last 1 event sent to a specific recipient...save the event to some variable...then output it to the console to view. 
I installed your package and have set up an example something like you see below:

var auth = require("../rest/payloads/people/mailgun.json");
var mailgun = require('mailgun-js')({apiKey: auth.apiKey, domain: auth.domain});
var output = mailgun.events().get(recipient='testman1@mg.casctesla.com',limit=1);
console.log(output);

Any guidance would be greatly appreciated

**Comment by jcurtis** [comment]
Hey @geosh03 - I haven't looked into your question at all yet but I recommend removing your API key from this public issue.

**Comment by bojand** [comment]
I've edited removed it as it's a security issue

**Comment by geosh03** [comment]
Follow up from my end:
I'm executing this command: 
            var opts = {limit: 1, recipient: 'testman1@mg.casctesla.com'};
            var output = yield mailgun.events().get(opts);
            console.log(output);

And getting the following output:
{ items: 
   [ { tags: [],
       timestamp: 1493051247.036047,
       storage: [Object],
       envelope: [Object],
       'recipient-domain': 'mg.casctesla.com',
       method: 'smtp',
       campaigns: [],
       'user-variables': {},
       flags: [Object],
       'log-level': 'info',
       id: '1eBcAqgQQA6x1t-tYx9nzA',
       message: [Object],
       recipient: 'testman1@mg.casctesla.com',
       event: 'accepted' } ],
  paging: 
   { next: 'https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2MyswMDowMCJ9LCB7ImEiOiBmYWxzZSwgImIiOiAiMjAxNy0wNC0yNFQxNjoyNzoyNy4wMzYrMDA6MDAifSwgWyJmIl0sIG51bGwsIFtbImFjY291bnQuaWQiLCAiNThmOTBiNTRmYTYwOTU0ZmIyY2JhYTg4Il0sIFsiZG9tYWluLm5hbWUiLCAibWcuY2FzY3Rlc2xhLmNvbSJdLCBbInJlY2lwaWVudCIsICJ0ZXN0bWFuMUBtZy5jYXNjdGVzbGEuY29tIl1dLCAxLCAibWVzc2FnZSMxZUJjQXFnUVFBNngxdC10WXg5bnpBIl0=',
     last: 'https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2MyswMDowMCJ9LCB7ImIiOiAiMTk3MC0wMS0wMVQwMDowMDowMC4wMDArMDA6MDAiLCAiZSI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2MyswMDowMCJ9LCBbInAiLCAiZiJdLCBudWxsLCBbWyJhY2NvdW50LmlkIiwgIjU4ZjkwYjU0ZmE2MDk1NGZiMmNiYWE4OCJdLCBbImRvbWFpbi5uYW1lIiwgIm1nLmNhc2N0ZXNsYS5jb20iXSwgWyJyZWNpcGllbnQiLCAidGVzdG1hbjFAbWcuY2FzY3Rlc2xhLmNvbSJdXSwgMSwgbnVsbF0=',
     first: 'https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2MyswMDowMCJ9LCB7ImEiOiBmYWxzZSwgImIiOiAiMjAxNy0wNC0yNFQxOTowNTo1Ny4wNjMrMDA6MDAifSwgWyJmIl0sIG51bGwsIFtbImFjY291bnQuaWQiLCAiNThmOTBiNTRmYTYwOTU0ZmIyY2JhYTg4Il0sIFsiZG9tYWluLm5hbWUiLCAibWcuY2FzY3Rlc2xhLmNvbSJdLCBbInJlY2lwaWVudCIsICJ0ZXN0bWFuMUBtZy5jYXNjdGVzbGEuY29tIl1dLCAxLCBudWxsXQ==',
     previous: 'https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2MyswMDowMCJ9LCB7ImIiOiAiMjAxNy0wNC0yNFQxNjoyNzoyNy4wMzYrMDA6MDAiLCAiZSI6ICIyMDE3LTA0LTI0VDE5OjA1OjU3LjA2NCswMDowMCJ9LCBbInAiLCAiZiJdLCBudWxsLCBbWyJhY2NvdW50LmlkIiwgIjU4ZjkwYjU0ZmE2MDk1NGZiMmNiYWE4OCJdLCBbImRvbWFpbi5uYW1lIiwgIm1nLmNhc2N0ZXNsYS5jb20iXSwgWyJyZWNpcGllbnQiLCAidGVzdG1hbjFAbWcuY2FzY3Rlc2xhLmNvbSJdXSwgMSwgIm1lc3NhZ2UjMWVCY0FxZ1FRQTZ4MXQtdFl4OW56QSJd' } }


I am looking for something like the following that includes "storage" portion:

{
  "items": [
    {
      "tags": [], 
      "timestamp": 1493051247.036047, 
      "storage": {
        "url": "https://se.api.mailgun.net/v3/domains/mg.casctesla.com/messages/eyJwIjpmYWxzZSwiayI6IjdkMjQ4ZDhjLTUzODYtNDI4ZS04ODFiLTQ3Y2NhNmZmNzdmNiIsInMiOiI3ZDg3ZDAzMTM1IiwiYyI6InRhbmtiIn0=", 
        "key": "eyJwIjpmYWxzZSwiayI6IjdkMjQ4ZDhjLTUzODYtNDI4ZS04ODFiLTQ3Y2NhNmZmNzdmNiIsInMiOiI3ZDg3ZDAzMTM1IiwiYyI6InRhbmtiIn0="
      }, 
      "envelope": {
        "targets": "testman1@mg.casctesla.com", 
        "transport": "smtp", 
        "sender": "0101015ba0c9f73d-60c6ee5e-7832-46ea-a300-954b5a787d3f-000000@us-west-2.amazonses.com"
      }, 
      "recipient-domain": "mg.casctesla.com", 
      "method": "smtp", 
      "campaigns": [], 
      "user-variables": {}, 
      "flags": {
        "is-authenticated": false
      }, 
      "log-level": "info", 
      "id": "1eBcAqgQQA6x1t-tYx9nzA", 
      "message": {
        "headers": {
          "to": "testman1@mg.casctesla.com", 
          "message-id": "0101015ba0c9f73d-60c6ee5e-7832-46ea-a300-954b5a787d3f-000000@us-west-2.amazonses.com", 
          "from": "CA Identity Service <no-reply@saasxsw.org>", 
          "subject": "Welcome to CA Identity Service"
        }, 
        "attachments": [
          {
            "filename": "linkimage.png", 
            "content-type": "image/png", 
            "size": 3542
          }, 
          {
            "filename": "header.png", 
            "content-type": "image/png", 
            "size": 4301
          }, 
          {
            "filename": "powered.png", 
            "content-type": "image/png", 
            "size": 4418
          }
        ], 
        "recipients": [
          "testman1@mg.casctesla.com"
        ], 
        "size": 15973
      }, 
      "recipient": "testman1@mg.casctesla.com", 
      "event": "accepted"
    }
  ], 
  "paging": {
    "next": "https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NiswMDowMCJ9LCB7ImEiOiBmYWxzZSwgImIiOiAiMjAxNy0wNC0yNFQxNjoyNzoyNy4wMzYrMDA6MDAifSwgWyJmIl0sIG51bGwsIFtbImFjY291bnQuaWQiLCAiNThmOTBiNTRmYTYwOTU0ZmIyY2JhYTg4Il0sIFsiZG9tYWluLm5hbWUiLCAibWcuY2FzY3Rlc2xhLmNvbSJdLCBbInJlY2lwaWVudCIsICJ0ZXN0bWFuMUBtZy5jYXNjdGVzbGEuY29tIl1dLCAxLCAibWVzc2FnZSMxZUJjQXFnUVFBNngxdC10WXg5bnpBIl0=", 
    "last": "https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NiswMDowMCJ9LCB7ImIiOiAiMTk3MC0wMS0wMVQwMDowMDowMC4wMDArMDA6MDAiLCAiZSI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NiswMDowMCJ9LCBbInAiLCAiZiJdLCBudWxsLCBbWyJhY2NvdW50LmlkIiwgIjU4ZjkwYjU0ZmE2MDk1NGZiMmNiYWE4OCJdLCBbImRvbWFpbi5uYW1lIiwgIm1nLmNhc2N0ZXNsYS5jb20iXSwgWyJyZWNpcGllbnQiLCAidGVzdG1hbjFAbWcuY2FzY3Rlc2xhLmNvbSJdXSwgMSwgbnVsbF0=", 
    "first": "https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NiswMDowMCJ9LCB7ImEiOiBmYWxzZSwgImIiOiAiMjAxNy0wNC0yNFQxOTowODo1MC43NDYrMDA6MDAifSwgWyJmIl0sIG51bGwsIFtbImFjY291bnQuaWQiLCAiNThmOTBiNTRmYTYwOTU0ZmIyY2JhYTg4Il0sIFsiZG9tYWluLm5hbWUiLCAibWcuY2FzY3Rlc2xhLmNvbSJdLCBbInJlY2lwaWVudCIsICJ0ZXN0bWFuMUBtZy5jYXNjdGVzbGEuY29tIl1dLCAxLCBudWxsXQ==", 
    "previous": "https://api.mailgun.net/v3/mg.casctesla.com/events/W3siYSI6IGZhbHNlLCAiYiI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NiswMDowMCJ9LCB7ImIiOiAiMjAxNy0wNC0yNFQxNjoyNzoyNy4wMzYrMDA6MDAiLCAiZSI6ICIyMDE3LTA0LTI0VDE5OjA4OjUwLjc0NyswMDowMCJ9LCBbInAiLCAiZiJdLCBudWxsLCBbWyJhY2NvdW50LmlkIiwgIjU4ZjkwYjU0ZmE2MDk1NGZiMmNiYWE4OCJdLCBbImRvbWFpbi5uYW1lIiwgIm1nLmNhc2N0ZXNsYS5jb20iXSwgWyJyZWNpcGllbnQiLCAidGVzdG1hbjFAbWcuY2FzY3Rlc2xhLmNvbSJdXSwgMSwgIm1lc3NhZ2UjMWVCY0FxZ1FRQTZ4MXQtdFl4OW56QSJd"
  }

**Comment by geosh03** [comment]
In my curl command, I am using a --data-urlencode which I believe is allowing me to see what is in the "storage" field. At this point, I only need help with adding that parameter correctly.

**Comment by geosh03** [comment]
Figured out issue
