### ISSUE TITLE
has no method 'messages'

### ISSUE THREAD

**Issue by imranallshore** [bojand/mailgun-js#138]
Hi i am facing issue to send email with module version 0.5.0. it showing me error message is not defined. i am using node 0.10.36 version. if i update the node version. its working fine. but i am not able to update the version of node due to other packages. i try to install different version of modules but problem is still exist.

**Comment by bojand** [comment]
0.5.0 had different API than what's documented...

```js
var Mailgun = require('mailgun-js')
var mailgun = new Mailgun({
  apiKey: 'key-my-api-key',
  domain: 'mydomain'
});

var params = {
  to: 'test@test.com',
  from: 'Me <me@outlook.com>',
  subject: 'Hello testing mailgun',
  text: 'testing message for mailgun'
};

mailgun.messages().send(params, function(err, body) {
  if (err) console.log(err.message);
  console.dir(body);
});
```

should work.

I would **highly** recommend you upgrade to newer Node.js LTS as 0.10 is end of life. Then you could use latest modules.

**Comment by imranallshore** [comment]
Thanks Sir,
Its Work. I am very thankful to you.
