### ISSUE TITLE
'Undefined' response

### ISSUE THREAD

**Issue by rjzheng** [bojand/mailgun-js#146]
I followed the code template, gave it my API key and the mailgun domain address that looks like "https://api.mailgun.net/v3/sandbox###########################.mailgun.org" and followed the rest of the template. However, when I ran my code/server, I get "Undefined" as the body response. Is it because I don't have my own domain set up? Or did I miss any steps?

**Comment by rjzheng** [comment]
I also tried "https://api.mailgun.net/v3/sandbox###########################.mailgun.org/messages", also doesn't work.

**Comment by bojand** [comment]
Hmm not sure I understand the issue. Some sample code would be helpful. You need to supply domain to the constructor:
```js
const mailgun = require('mailgun-js')({apiKey: api_key, domain: 'sandbox12345.mailgun.org'});
```

**Comment by rjzheng** [comment]
yea I had trouble figuring out the correct domain String. Got it to work! Thanks!
