### ISSUE TITLE
email validation: private token (feature)

### ISSUE THREAD

**Issue by zxfrank** [bojand/mailgun-js#147]
Hello,
this is more as information and feature request...
in order to use "private" token to validate email address, you need to add it in the url like this:

`
Mailgun.prototype.validatePrivate = function (address, fn) {
  var resource = `/address/private/validate`;
  var options = this.getRequestOptions(resource);

  var req = new Request(options);
  return req.request('GET', resource, { address }, fn);
};`

**Comment by bojand** [comment]
Implemented and published as `0.12.0`. This should work now:

```js
mailgun.validate('test@email.com', true, function (err, body) {
  console.log(body);
});
```

**Comment by zxfrank** [comment]
nice! thanks!

**Comment by kildem** [comment]
I've done this:
`const mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});
const cb = (err, body) => {
			console.log("body: ", body, " err: ", err);
			if (body && body.is_valid) {
				console.log("is valid");
			}
		});
mailgun.validate(email, true, cb);`

but it prints this message:
`body:  undefined  err:  { Error: Unauthorized
        at IncomingMessage.<anonymous> (.../node_modules/mailgun-js/lib/request.js:301:15)
        at emitNone (events.js:110:20)
        at IncomingMessage.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1059:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9) statusCode: 401 }
`
my api_key is correct. Why I receive "Unauthorized" message? What I'm missing?

**Comment by kvz** [comment]
Was unable to find this in the docs until I hit this issue, just a friendly note to maybe add it to the readme ❤️

**Comment by bojand** [comment]
Hello, it's documented [here](http://bojand.github.io/mailgun-js/#/email_validation), but I agree it should be clearer in the readme. Added function docs to the readme.
