### ISSUE TITLE
Track Successful Deliveires

### ISSUE THREAD

**Issue by jmelendev** [bojand/mailgun-js#148]
I may have missed this somewhere, but can we track if the email was delivered (not only accepted) using this module?

**Comment by bojand** [comment]
You can track events including deliveries using any mechanism as described in the [tracking](https://documentation.mailgun.com/en/latest/user_manual.html#tracking-messages) documentation. Specifically you can use this module to [query](http://bojand.github.io/mailgun-js/#/api/events) the [events api](https://documentation.mailgun.com/en/latest/api-events.html#query-options). For example:

```js
mailgun.messages().send(params, (err, body) => {
  if (err) console.error(err.message);
  console.log(body);
  mailgun.events().get({event: 'delivered'}, (err, events) => { 
    if (err) console.error(err.message);
    console.dir(events.items, {depth: 2, colors: true})
  })
})
```

Additionally this module can help you set up your webhooks by providing the [webhook validation function](http://bojand.github.io/mailgun-js/#/webhook).
