### ISSUE TITLE
Unexpected token error in the lib (node_modules/mailgun-js/lib/mailgun.js:153)

### ISSUE THREAD

**Issue by mustafabereket** [bojand/mailgun-js#149]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
"mailgun-js": "~0.11.2"

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
AWS Linux 
Node v0.10.25

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
Doesnt work at all, runtime error

4) Sample source code or steps to reproduce
I have a very simple application requires mailgun-js, when it hits the when I construct mailgun with my key and domain, it gives me this following error:

/var/www/offlineAlert/node_modules/mailgun-js/lib/mailgun.js:153
  var resource = `/address/validate`;
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/offlineAlert/app.js:9:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I tried uninstalling and re-installing it again couple of times, but it didnt work. 

I am not sure what to do at this point.

**Comment by bojand** [comment]
As specified in `package.json`'s `engine` property, this module requires Node.js version 4.0 or above. I strongly recommend you upgrade to the current LTS as 0.10 is not event getting security fixes like the latest [security update](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/).
