### ISSUE TITLE
Send mail, and return undefined

### ISSUE THREAD

**Issue by felixfong227** [bojand/mailgun-js#150]
8.0.0 on Mac OS X

```javascript
const mailgun = new Mailgun({
    apiKey: <API key>,
    domain: <API Base URL>,
});

const data = {
    from: '<Default SMTP Login>',
    to: user.email,
    subject: '<Subjet>',
    html: `<context>`
}

mailgun.messages().send(data, function (err, body) {
    if (err) {
        console.log("got an error: ", err);
    }
    else {
        console.log(body);
    }
});
```

When I try to log out the body, It just keep returning `undefined` but didn't return an error?

**Comment by jmwright** [comment]
I'm having the same problem.

Node: 8.1.4 (via NVM)
mailgun-js: 0.11.3
OS: Ubuntu 16.04

**Comment by bojand** [comment]
Hmm I cannot reproduce this at all. Tried it with 8.0.0, and 8.1.4 (both installed via nvm) and 8.2.1 natively installed, on mac os x and it all works. Also we use this module in production fairly extensively and have for a while, and AFAIK we haven't seen this, thought I am not sure if we specifically check for the `body` off the top of my head. 

That being said, a few things:
* is this consistent or sporadic?
* if consistent, does an equivalent curl or postman (or other http client) request yield same or different behaviour.
* adding debug logging via `DEBUG=mailgun-js` environment variable might provide some clues to what's going on

**Comment by jmwright** [comment]
For me the problem is consistent, and curl works fine. I should also note that the email never sends with mailgun-js. It will send if I use curl though.

When I use the `DEBUG` environment variable, here's what I get. The x's after the V3 were put there by me since I figured that identified my account, and the "undefined" on the line by itself is from a `console.log` that I added.

```
  mailgun-js POST /v3/https://api.mailgun.net/v3/sandboxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mailgun.org/messages/messages +0ms
POST /contactform 200 310.285 ms - -
  mailgun-js response status code: 200 content type: application/octet-stream error: undefined +179ms
undefined
```

**Comment by jmwright** [comment]
@bojand I'm posting my code in the hopes that it will help highlight something I'm doing wrong. I've anonymized the code where necessary.

```javascript
  var api_key = 'key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
  var domain = 'https://api.mailgun.net/v3/sandboxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mailgun.org/messages';
  var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});

  var data = {
    from: 'Mailgun Sandbox <postmaster@sandboxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mailgun.org>',
    to: 'User <user@gmail.com>',
    subject: 'Hello',
    text: 'Testing some Mailgun awesomness!'
  };

  mailgun.messages().send(data, function (error, body) {
    if (error) {
        console.log(error);
    }
    else {
      console.log(body);
    }
  });
```

**Comment by bojand** [comment]
Hmm domain should just be something like: `sandbox12345.mailgun.org`.
http://bojand.github.io/mailgun-js/#/?id=options

**Comment by jmwright** [comment]
Ok, thanks. I went to https://app.mailgun.com/app/domains and found the correct domain for my account. I had tried domains from other sources, but the one I found there works.

**Comment by jmwright** [comment]
@felixfong227 Can you confirm if this fix worked for you? I accidentally hijacked your issue.

**Comment by jschr** [comment]
Spent a while debugging this same error before I came across this issue. I was using the full api url `https://api.mailgun.net/v3/<domain>` instead of just `domain`. 

Definitely a user error but a proper error message would have helped. Even if it was just an 'invalid domain' error.

**Comment by zzxoto** [comment]
@jschr  Wow Thanks man.

**Comment by bojand** [comment]
This is documented?

http://bojand.github.io/mailgun-js/#/?id=options

> domain - Your Mailgun Domain (Please note: domain field is MY-DOMAIN-NAME.com, not https://api.mailgun.net/v3/MY-DOMAIN-NAME.com)

**Comment by zzxoto** [comment]
Of course, how blind of me. Anyway the proper error message would have been a lot convenient.

**Comment by sulenchy** [comment]
![Uploading Screen Shot 2020-05-31 at 6.18.54 PM.png…]()

Thank you all for sharing your experience. Here is my experience. I agreed with you all that a proper error message would have saved the day for any developer having this issue. In addition to that, I think mailgun would have to make copying the domain a lot easier by adding a copy functionality(like click board icon) to that page. Most newbies just get the URL instead of the domain itself. The domain is the part that starts with `sandbox...`.

**Comment by Engineersticity** [comment]
Thanks. This helped alot!

**Comment by sulenchy** [comment]
Wow, I sent that a very long time ago. I can't even remember the feedback
specifically. However, I am happy the feedback helps.

Regards.

**Comment by lexycole** [comment]
> Thank you all for sharing your experience. Here is my experience. I agreed with you all that a proper error message would have saved the day for any developer having this issue. In addition to that, I think mailgun would have to make copying the domain a lot easier by adding a copy functionality(like click board icon) to that page. Most newbies just get the URL instead of the domain itself. The domain is the part that starts with sandbox....

This works!!!https://assets.grammarly.com/emoji/v1/270c.svg
