### ISSUE TITLE
Issues sending an email with an image in the body

### ISSUE THREAD

**Issue by ptums** [bojand/mailgun-js#161]
Hello,

I want to send an email with an image in the body. I can't seem to find any documentation on how to accomplish this. If there is any documentation where would I find it?  I tried sending both the file itself from where it is stored on my computer in the email and in a base64 format, neither have worked.

Any direction would be greatly appreciated .

Thank you! 

Here is my code 
```
function congratulationsTemplate(message){
  // This line grabs the image I have stored in an uploads folder inside my directory
 // This approach isn't working and I tried sending it in a base64 format and that isn't working either.
  var image = path.join(__dirname, "../uploads/"+message.file).toString();
  var data ={
    from:'',
    to:'',
    subject: message.title,
    html: "<h1>Hello World</h1><p>Here is an image:<br/> <img src='+image+'/></p>",
    attachment: image
  };

  mailgun.messages().send(data, function (error, body) {
    if(error) throw error;
    console.log("Message Sent!");
  });
}
```

**Comment by bojand** [comment]
Hello,

That can be accomplished using the `inline` param. Here's all the relevant documentation:

http://bojand.github.io/mailgun-js/#/attach

> Attachments can be sent using either the attachment or inline parameters. inline parameter can be use to send an attachment with inline disposition. It can be used to send inline images. Both types are supported with same mechanisms as described, we will just use attachment parameter in the documentation below but same stands for inline.

https://documentation.mailgun.com/en/latest/api-sending.html#sending

See `inline` param. REST example in the guide:

https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-api

And here's sample code in the tests:

https://github.com/bojand/mailgun-js/blob/master/test/mailgun.test.js#L190

```js
var msg = clone(fixture.message);
var filename = path.join(__dirname, '/mailgun_logo.png');

msg.inline = filename;

mailgun.messages().send(msg, function (err, body) {
  // ...
});
```

**Comment by ptums** [comment]
Thank you! This worked. It may help to edit this example to show people trying to add an inline image what the code should look like in the html key.

For example

```
var filename = path.join(__dirname, '/mailgun_logo.png');
var data ={
from: ...,
to: ...,
subject: ...,
html: '<div><img src="cd:mailgun_logo.png"/><h1>Thank you for choosing Mailgun!</h1></div>';
inline:filename
}

**Comment by captDaylight** [comment]
@ptums all of that looks good, except instead of:
```src="cd:mailgun_logo.png"```
you need
```src="cid:mailgun_logo.png"```

**Comment by masaguaro** [comment]
For anyone using `inline`, it is necessary to add `rb` as a parameter to the constrctor in `files=[("inline", open("files/test.jpg"))]`. There is an error in the documentation:

[https://documentation.mailgun.com/en/latest/user_manual.html?highlight=inline%20images#sending-via-api](url)

 Please, check it here for the solution:

[https://github.com/mailgun/documentation/issues/280](url)

**Comment by bander-saeed94** [comment]
please example for how to add rb

**Comment by vadbut** [comment]
Based on the discussion above, I tried adding an image inline as follows:
```
var data = {
    from: '...',
    to: '...',
    subject: '...',
    text: `...`
  }; 
  var filename = request("https://raw.githubusercontent.com/vadbut/misc_stuff/master/logo3_face_footer.jpg");
  data.inline = filename;
  
  mailgun.messages().send(data, function (error, body) {
    console.log(body);
  });
```
However, the image arrives in attached.
What did I miss?

**Comment by BHS551** [comment]
@vadbut did you add the cid of the image in the template ?

**Comment by thuydtran** [comment]
Hi,

I got the email without the image embedded.  Below is the code.  Any clue please let me know. Thanks. 

var src= "https://cdn.shopify.com/s/files/1/0170/8074/6048/products/QQ_505.jpg?v=1569900210";
var fileName = "cid:" + "request(\"" + src + "\")";
//var fileName = "cid:" + src; 

var req1 = ...
req1.inline= fileName;
mailgun.messages().send(req1, function(error, body) {
        console.log(body);
});
