### ISSUE TITLE
Issues with query using .get method 

### ISSUE THREAD

**Issue by ptums** [bojand/mailgun-js#166]
Hello,

I am in need of some direction on how to structure a query to the ```/events``` endpoint. What I am trying to get back is a list of all the emails by subject and along with it whether they've been opened and clicked on, and the amount of people it was sent too. 

This is my code below:

```
  var getWelcomeStats = mailgun.get("/scarincilaw.com/events", {limit:100, event:["accepted", "delivered", "opened", "clicked"] });
  getWelcomeStats.then(function(data){
    data.items.forEach(function(val){
      console.log(val);
      res.send(val);
    });
  });
```
Is there something I am missing? 

Any direction or advice would be greatly appreciated 

Thank you,

Peter

**Comment by bojand** [comment]
If you look at the mailgun [events documentation](https://documentation.mailgun.com/en/latest/api-events.html#events), the `event` parameter is a filter expression. So you could do something like:

```js
const query = {
  limit: 100,
  event: 'accepted OR delivered OR opened OR clicked'
}
// assuming mailgun was created using the domain you wish to query
mailgun.events().get(query, (err, data) => {
  console.log(data)
})
```
That query may get you more than what you're looking for; to me it sounds more like you would want just `'opened OR clicked'` but that depends on your specific context.

Note that `opened` and `clicked` events have special requirements for tracking as [documented](https://documentation.mailgun.com/en/latest/api-events.html#event-types).

**Comment by ptums** [comment]
Wow thank you for your help! You've been kind. If you ever want help in the project let me know I'd be happy to contribute.

**Comment by ptums** [comment]
Basically what I am trying to do is query the subject line of the email, the amount of ppl it was sent too, how many ppl opened it, and how many ppl clicked on the email.  Any way to query that exact info that would be incredible!
