### ISSUE TITLE
when i import mailgun-js i get this

### ISSUE THREAD

**Issue by bardiaheshmati** [bojand/mailgun-js#167]
W20170904-12:17:22.235(8)? (STDERR) Error: Cannot find module './attachment'
W20170904-12:17:22.235(8)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20170904-12:17:22.236(8)? (STDERR)     at require (packages/modules-runtime.js:231:19)
W20170904-12:17:22.236(8)? (STDERR)     at meteorInstall.node_modules.mailgun-js.lib.mailgun.js (packages/modules.js:605:18)
W20170904-12:17:22.236(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170904-12:17:22.236(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170904-12:17:22.237(8)? (STDERR)     at meteorInstall.imports.api.Email.server.methods.js (imports/api/Email/server/methods.js:1:15)
W20170904-12:17:22.237(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170904-12:17:22.237(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170904-12:17:22.237(8)? (STDERR)     at meteorInstall.imports.api.Email.index.js (imports/api/Email/index.js:1:14)
W20170904-12:17:22.238(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)

this is just upon importing the library, no other codes are added

**Comment by bojand** [comment]
Please provide some context and code and steps to reproduce as the issue template instructs. This seems meteor related... which I am not completely familiar with. Is this from webpack? Are you trying to use the module client side? This module is intended to be used server side within Node.js environment.
