### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by lpellegr** [bojand/mailgun-js#178]
This library is really awesome but what a shame there is no native promises support. Are there any plans?

**Comment by bojand** [comment]
Hello, the library already has native promise support. I have updated the relevant [documentation](http://bojand.github.io/mailgun-js/#/promises) as it was outdated and referenced the `Q` library when we used that in our implementation, which was a while ago. Example usage:

```js
const mailOptions = {
  // ...
}

mailgun.messages().send(mailOptions).then(res => {
  console.log(res)
}).catch(err => {
  console.log(err)
})
```
with `async` + `await`:

```js
const mailOptions = {
  // ...
}

async function main () {
  const res = await mailgun.messages().send(mailOptions)
  console.log(res)
}

main()
```
