### ISSUE TITLE
mailbox_verification type

### ISSUE THREAD

**Issue by ShawnPavel** [bojand/mailgun-js#179]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
> 0.13.1

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
> Node 8.9.1
> MacOs

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
> Yes

4) Sample source code or steps to reproduce
> Validate email with mailbox_verification enabled:

```
this.mg.validate(
    firebaseUser.email, 
    true, 
    { mailbox_verification: true }, 
    (err: any, body: any) => {
        // read body here
    }
);
```

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
> The `mailbox_verification` member has a string value, whereas the other boolean values are booleans (as you can see in the object below). Can we have mailbox_verification switched to also have a boolean type for consistency?

```
{
    "address": "939282j2nnj9@gmail.com",
    "did_you_mean": null,
    "is_disposable_address": false,
    "is_role_address": false,
    "is_valid": true,
    "mailbox_verification": "false",
    "parts": {
        "display_name": null,
        "domain": "gmail.com",
        "local_part": "939282j2nnj9"
    },
    "reason": null
}
```

**Comment by ShawnPavel** [comment]
I see that the documentation actually provides the `mailbox_verification` member as a string as well. 

https://documentation.mailgun.com/en/latest/api-email-validation.html

**Comment by bojand** [comment]
Sorry I am not really understanding the issue... Can you elaborate further and provide a reproducible sample code? I am guessing this is somehow related to the TypeScript typings that you are using for this module?

**Comment by ShawnPavel** [comment]
Hey @bojand,
I'm not using any typings so that's not the problem. It's simply an issue with the json object. Looking at the json object above you can see the following two properties:

```
"is_valid": true,
    "mailbox_verification": "false",
```

Notice how the `"false"` value of mailbox_validation has quotes around it? It's a json string. Whereas all the other Boolean values do not have quotes. 

Non empty string evaulate as `truthy` in JavaScript as I'm sure you know. So a value of `"false"` would evaluate as true in an if statement.

This is how the data is returned from the mailing api, so I don't think it's an issue with the plugin. I suppose it's just something to be aware of so that it can be properly handled by the developer.
