### ISSUE TITLE
Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by 0x1ad2** [bojand/mailgun-js#195]
**1) What version of the module is the issue happening on? Does the issue happen on latest version?**
0.16.0

**2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)**
v7.10.0 (npm v5.6.0), MacOS

**3) Does the action work when you manually perform request against mailgun using curl (or other means)?**
Yes, mailgun is configured perfectly, when doing a cURL my message gets queued and send.

**4) Sample source code or steps to reproduce**
- npm i mailgun-js
- import mailgun from 'mailgun-js';
- mailgun({ apiKey, domain }).messages().send(data, (error, body) => { console.log(body); });
- and ofcourse the apiKey, domain and data are set

**Comment by surielmx** [comment]
Hi, I have the same issue with NPM 5.8.0 and NODE 9.7.1, any solution?
![screen shot 2018-04-16 at 4 26 04 pm](https://user-images.githubusercontent.com/1803166/38836209-eb0043cc-4192-11e8-8a6a-0b44de9e4d47.png)

**Comment by bojand** [comment]
Hello, where does `Failed to compile` come from?

**Comment by KeepingItClassy** [comment]
I'm experiencing the same error. Using Mailgun as an add-on in a Heroku React app. I'm getting this error in the browser after running `heroku local`. @bojand, please advise how to fix this or work around it.

**Comment by bojand** [comment]
https://github.com/bojand/mailgun-js#usage-overview

> This module is intended to be used within Node.js environment and **not** from the browser. For browser use the [mailgun.js](https://github.com/mailgun/mailgun-js) module.
