### ISSUE TITLE
Error: 'to' parameter is not a valid address. 

### ISSUE THREAD

**Issue by zzxoto** [bojand/mailgun-js#199]
1) What version of the module is the issue happening on? Does the issue happen on latest version?

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
>>>Node.js vs 9.3.0 Windows 10 64bit
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
>>> Mailgun 0.16.0

4) Sample source code or steps to reproduce
>>>
	try{
		var filepath = path.join(__dirname, "../../../logs", data.filename);//filename inside logs.
		await mailgun.messages().send({
			from: mailConfig.no_reply,
			to: mailConfig.admin,
			subject: 'Report Attachments To Admin',
			text: 'Hello',
			attachment: filepath
		});
	}
	catch(err){
		errLogger({err});
	}

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

"""Error: 'to' parameter is not a valid address. please check documentation""". I am getting this error mesage in my catch block although the emailget sent succesfully. to parameter is 'myGmail@gmail.com'

**Comment by bojand** [comment]
Hello,

This is a response from mailgun API when you use an invalid email in the `to` parameter. For example using curl if we did something similar to:

```
curl -s --user 'api:key-mailgun-api-key' \
    https://api.mailgun.net/v3/sandbox000000.mailgun.org/messages \
    -F from='someemail@outlook.com' \
    -F to='otheremail@gmailcom' \
    -F subject='Hello' \
    -F text='Testing some Mailgun awesomeness!'
{
  "message": "'to' parameter is not a valid address. please check documentation"
}
```

Note that something like `otheremail@gmailcom` is not a valid email address. If we fix the domain with `gmail.com` it works.
