### ISSUE TITLE
mailgun-js causes Uninitialized High severity Memory Exposure error in snyk.io

### ISSUE THREAD

**Issue by deejbee** [bojand/mailgun-js#201]
1) What version of the module is the issue happening on? Does the issue happen on latest version?

mailgun-js@0.16.0

Report from snyk.io about the out of date component:

Introduced through: ui-data-api@0.1.0 › mailgun-js@0.16.0 › proxy-agent@2.1.0 › pac-proxy-agent@2.0.0 › https-proxy-agent@1.0.0
Remediation: Your dependencies are out of date, otherwise you would be using a newer https-proxy-agent than https-proxy-agent@1.0.0. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: ui-data-api@0.1.0 › mailgun-js@0.16.0 › proxy-agent@2.1.0 › https-proxy-agent@1.0.0

**Comment by bojand** [comment]
Hello,

This should be addressed with #202 and fixed in `0.17.0`.
