### ISSUE TITLE
 Denial of Service vulnerability on http-proxy-agent@1.0.0 and https-proxy-agent@1.0.0

### ISSUE THREAD

**Issue by radu-andrei-28** [bojand/mailgun-js#205]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
Version no: **0.7.15**
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
Node version: **6.12.2**

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)¨

Hi,
After running our project through retire.js I have discovered the following vulnerability.

Retire.JS report:
http-proxy-agent 1.0.0 has known vulnerabilities:  severity: high; summary: Denial of Service; https://hackerone.com/reports/321631

It seems that mailgun is using proxy-agent@2.0.0 (3.0 available) which uses an outdated version of http-proxy-agent@1.0.0 + https-proxy-agent@1.0.0

**Issue:**
This version of http-proxy-agent is vulnerable to Denial of Service attacks.

**Comment by bojand** [comment]
the relevant dependencies were updated in version 0.17.0.
