### ISSUE TITLE
Socket hang up error on AWS Lambda

### ISSUE THREAD

**Issue by unleashit** [bojand/mailgun-js#206]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.18.0
Yes

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
8.1 on AWS Lambda

3) Does the action work when you manually perform request against mailgun using curl (or other means)?

Yes

4) Sample source code or steps to reproduce

Sending email from AWS Lambda is failing. Most of the time silently with the callback not firing, but a couple of times I've seen:

 { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'ECONNRESET',
  path: null,
  host: 'api.mailgun.net',
  port: 443,
  localAddress: undefined }

Any ideas? I've tried increasing the timout to 5 sec, 3 retries, and have also increased the allotted time in Lambda to 20 secs. The exact same code is working offline.

**Comment by unleashit** [comment]
Firgured out my problem. I am declaring context.callbackWaitsForEmptyEventLoop = false, which freezes the process when the Lambda callback is called. Just needed to ensure it was called after the mailgun callback returns. Working now, so closing this!

**Comment by jeremygiberson** [comment]
@unleashit Just wanted to say things for following up on your issue when you found the source of the problem. Was running into something similar in our ecosystem and could not figure out what was causing this hang up. You just made my day -- cheers!
