### ISSUE TITLE
Can only get 100 records.

### ISSUE THREAD

**Issue by binarymist** [bojand/mailgun-js#207]
Does anyone have any pointes how to get list records over 100?
```
await internals.list.members().pages().page({subscribed: true}).then(
    async function (members) {
      debugger;
      // `members` is the list of members


      await internals.mailgun.get(members.paging.next).then(
        (data) => {
          debugger;
        }, (err) => {
          debugger;
        }
      );
```
works fine for the first 100, and supposedly provides links for the next, etc, but those links don't seem to work. I've also tried using a [`mailgun.get`](https://github.com/bojand/mailgun-js#generic-requests) and that hasn't worked. I've used the `request` lib and I get some message from mailgun like "The great mailgun API".

**Comment by bojand** [comment]
What's the `debugger` stuff?
Did you get this resolved based on the [comment](https://github.com/bojand/mailgun-js/issues/125#issuecomment-396894718) in #125 ?

**Comment by binarymist** [comment]
`debugger` stuff is for inspection during development. I appear to have it working (thanks to [@ewagoner](https://github.com/bojand/mailgun-js/issues/125#issuecomment-311861881) of ) Once I've tidied this up and pushed it, I'll provide sample code and link. Thanks.

**Comment by Blackbaud-SteveBrush** [comment]
Another way to do this, set the `limit` to something more than your number of users:
```
const limit = 1000;
const mailingListName = 'updates@mg.foobar.com';

return mailgun.get(`/lists/${mailingListName}/members/pages?limit=${limit}`)
  .then((results) => {
    return results.items;
  });
```
