### ISSUE TITLE
data-uri-to-buffer error since 0.20.0

### ISSUE THREAD

**Issue by sam0971** [bojand/mailgun-js#214]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
Version used: 0.20.0

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
Node 8.9.4

Since we updated to mailgun v 0.20.0 we received the following error from our error tracking system:
`Error: Cannot find module 'data-uri-to-buffer'`

The line where this error occured was exactly on the line where we instantiate the mailgun plugin.
`const mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});`

Adding `data-uri-to-buffer` to our package.json fixed the problem and we were again able to receive emails. Should this be added as a dependency for mailgun or is there something else going on? The previous version of mailgun worked perfectly for us.

**Comment by bojand** [comment]
Hmm that is strange... I can't reproduce this with Node.js 8.9.3, using `npm` (version 5.5.1 which comes with Node.js 8.9.3) or `yarn` 1.5.1. Also works with latest Node.js 10.6.0 (npm v6.1.0). What OS? Are you using a different registry (ie artifactory or something similar)?

**Comment by sam0971** [comment]
We had this error on google app engine (using the Google-maintained Node.js docker image based on Debian Jessie). But also locally on mac os x 10.13.5 I received the same error after updating to mailgun 0.20.0. 
We're not using a different registry.

**Comment by sam0971** [comment]
Now we can't reproduce this issue also anymore. I think something went wrong with our npm install.
