### ISSUE TITLE
docs do not use 'new' keyword for class constructor

### ISSUE THREAD

**Issue by Benjmhart** [bojand/mailgun-js#237]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
latest
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
all
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
n/a
4) Sample source code or steps to reproduce
n/a
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

your docs should use the new keyword when instantiating the Mailgun class to prevent pollution of 'this' object unintentionally passed into the constructor (global/window)

**Comment by bojand** [comment]
Hello, this library used to expose a class where the client needed to create an instance a while ago; but it was changed in #46 to address #45 to expose a single already created instance of the class for convenience. Regardless, this is a Node.js-only module and does not work in browser (`window` does not apply), and it does not mutate the [global object](https://nodejs.org/api/globals.html).
