### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by stupax** [bojand/mailgun-js#239]
Hi,
I am using mailgun-js@0.22.0 with Node.js v8.15.1 on Mac

I am getting a Forbidden Error: , here is my code -

 const emailConfig = {
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
    domain: 'mail.cloud-invoices.co.uk',
    host: 'api.eu.mailgun.net'
  };
  var mailgun = require('mailgun-js')(emailConfig);

  const data = {
    from: 'Excited User <info@mail.cloud-invoices.co.uk>',
    to: 'info@bigswebdesign.co.uk',
    subject: 'Hello',
    text: 'Testing some Mailgun awesomness!'
  };

  mailgun.messages().send(data, (error, body) => {
    if(error) throw error;
    console.log(body);
  });

Any ideas?

Thanks,
Stewart

**Comment by SixBytesUnder** [comment]
Hi @stupax 
Have you solved your issue? I have the exact same problem and would love to know if you have a fix for it.

**Comment by BenjaminWatts** [comment]
I think you have to instruct the client that you're using a European domain:

`const client = mailgun.client({
  host: "api.eu.mailgun.net",
  username: 'api',
  key: 'YOUR-KEY',
});`
