### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by LoganDark** [bojand/mailgun-js#240]
![Bitmap](https://user-images.githubusercontent.com/4723091/57328678-e9365b80-70c6-11e9-883c-4ad5f32490aa.png)

These.

How do I use these with the library?

**Comment by LoganDark** [comment]
This library doesn't seem to have any support for templates whatsoever. I can't find any via code search anyway, because it uses some completely weird schema setup which obfuscates what the code's actually doing. So I'm left at a complete loss and I have absolutely _no_ idea what I should do.

I'll probably be ditching this library and sending requests on my own.

**Comment by atrites** [comment]
Good luck! If you end up doing it the repo is always open to pull requests.

**Comment by LoganDark** [comment]
I can't figure out how to add any options to the library because everything is obfuscated behind some overcomplicated Builder setup with a JSON schema.

**Comment by Samstiles** [comment]
@bojand HOW DARE YOU

**Comment by bojand** [comment]
Hello,

Thank you for your inquiry regarding the support of the templates API. Unfortunately, as the README states this library is [not maintained](https://github.com/bojand/mailgun-js#maintenance-notice) any more, so indeed it is missing this feature. It's not archived to allow people to submit pull requests and offer help to each other in issues and comments.

With regards as to how the library functions, it's actually not too complicated, albeit perhaps not immediately clear. It uses [JSON Schema](https://json-schema.org/) of the [API](https://github.com/bojand/mailgun-js/blob/master/lib/schema.js) to build different object and actions for different parts of the API, as they are specified in the JSON schema. This approach is easier and more convenient than hand writing each individual API and request by hand. There are other approaches that could be done to accomplish similar effect, but this is how we did it when we started the library over 6 years ago... With respect to adding a new API (such as templates), it is relatively simple. All it would involve is adding the correct JSON schema representation of the API with correct paths, methods, etc...

Regards,

Bojan

**Comment by LoganDark** [comment]
> it's actually not too complicated, albeit perhaps not immediately clear. It uses JSON Schema of the API to build different object and actions for different parts of the API, as they are specified in the JSON schema

That's what I'm saying. The class that reads the JSON schema and builds methods based on it is incredibly hard to understand, and the JSON schema itself gives me little to no idea what's actually going on.

> This approach is easier and more convenient than hand writing each individual API and request by hand.

No, it's not. It's incredibly confusing and only serves to discourage pull requests by making the code needlessly complicated.

> With respect to adding a new API (such as templates), it is relatively simple. All it would involve is adding the correct JSON schema representation of the API with correct paths, methods, etc...

There's no way to do custom headers in your schema, as far as I can tell. Of course, I probably can't tell because it's the most ridiculous thing I've ever seen in a library.

---

Your whole idea of a schema ruins any chance I had of understanding how the hell I'm supposed to add any functionality to the library. Even if I were to add a template argument, it wouldn't be enough becuase you'd need the X-Mailgun-Variables header too. And I'm not touching that awful builder class that generates methods from the schema. I took one look at it and [nope](https://www.youtube.com/watch?v=5FjWe31S_0g).

So yeah, I'm ditching this library and writing my own. This is much more complicated than it needs to be, I'm not going to pour my time and effort into finding a solution when my deadline is in 10 days.

**Comment by poliha** [comment]
In case any one has this issue, all you need to do is call send() like this

```javascript
  mailgun.messages().send({
  ...otherParams,
  template: 'yourTemplateName',
  'h:X-Mailgun-Variables': JSON.stringify({
     name: 'abc',
     title: 'xyz',
     // other params..
  })
});
```
