### ISSUE TITLE
Undefined error on basic example

### ISSUE THREAD

**Issue by andreyshedko** [bojand/mailgun-js#241]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.22.0
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
10.7.0
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
I do not have curl on Windows.
4) Sample source code or steps to reproduce
```
import MailObject from "./MailObject";
import { Request, Response } from "express";
const mailgun = require("mailgun-js")({ apiKey: process.env.MAILGUN_API_KEY, domain: process.env.MAILGUN_DOMAIN });

export default class APIController {

    public static sendEmail(req: Request, res: Response) {
        const mail = new MailObject(req.body.from, req.body.subject, req.body.to, req.body.templateId);
        APIController.sendMailViaMailGun(mail);
    }

    private static sendMailViaMailGun(mail: MailObject) {
        const data = {
            from: `Zapas.tech <${mail.from}>`,
            to: mail.to,
            subject: mail.subject,
            text: "Testing some Mailgun awesomness!"
        };
        mailgun.messages().send(data, (error: any, body: any) => {
            console.log("err", error);
        });
    }
}
```
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
The error happens when I'm trying to send email, error value from console.log is `undefined`

**Comment by andreyshedko** [comment]
If I change the domain from `https://api.eu.mailgun.net/v3/mail.zapas.tech` to `mail.zapas.tech`, I'm getting error `Domain not found `

**Comment by mcclowes** [comment]
@andreyshedko what was wrong in the end?
