### ISSUE TITLE
BCC with recipient-variables

### ISSUE THREAD

**Issue by ericln** [bojand/mailgun-js#89]
I am trying to do batch send with `recipient-variable` and html/text template. Normal email with only `to` recipients works, however, when I added `bcc` recipients, the bcc recipient's email body is not getting populated with the variable supplied.

this is what i have 

```
var data = 
{
      from: 'From <name@comething.com>'),
      to: ['Person1 <p1@something.com>', 'Person2 <p2@something.com'],
      bcc: ['Person2 <p2@something.com>'],
      subject: 'Subject',
      text: 'text body with some token in the body',
      html:  'html body with some token in the body'
};

data['recipient-variables'] = 'variable data here';

mailgun.messages().send(data, callback);

```

any thought?

**Comment by bojand** [comment]
Hello,

Seems to work for me...

For example:

```js
var params = {
  to: ['Person1 <email1@gmail.com>'],
  bcc: ['Person2 <email2@gmail.com>'],
  from: 'Me <me@outlook.com>',
  subject: 'Hey, %recipient.first%',
  text: 'testing message for mailgun',
  html: 'HTML version of body'
};

params['recipient-variables'] = {
  "email1@gmail.com": {
    first: 'Person1Name'
  },
  "email2@gmail.com": {
    first:"Person2Name"
  }
};

mailgun.messages().send(params, function(err, body) {
  if (err) console.dir(err.message);
  console.dir(body);
});
```

I have also verified that setting the `'recipient-variables'` property to strigified version of the data works as well. What I did notice was that it doesn't work if you only include data for the `bcc` recipient. so for example:

```js
params['recipient-variables'] = {
  "email2@gmail.com": {
    first:"Person2Name"
  }
};
```

Will actually not work. I have verified this using curl as well... So for example:

```sh
curl -s --user 'api:key-MY-MAILGUN-KEY' https://api.mailgun.net/v3/DOMAIN.mailgun.org/messages -F from='Me <me@outlook.com>' -F to=email1@gmail.com -F bcc=email2@gmail.com -F recipient-variables='{"email2@gmail.com":{"first":"Person2Name"}}' -F subject='Hey, %recipient.first%' -F text='Some sample text'
```

Will not work, and will not populate the BCC recipient variable. Please try it and let me know. If you can reproduce I would suggest perhaps contacting mailgun and submitting a ticket.

**Comment by ericln** [comment]
your example works, thanks, but there is another issue I guess this is a mailgun thing, the bcc person is receiving the email as it was addressed to them instead of being part of the bcc. Do you have any insight on that? i'll check with mailgun as well see if that's the expected behaviour, certainly not from how I understand bcc should work.
