### ISSUE TITLE
Sending to Mailing List

### ISSUE THREAD

**Issue by lunedam-git** [bojand/mailgun-js#97]
1) What version of the module is the issue happening on? Does the issue happen on latest version?

0.7.11

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)

Node.js 4.4.4 on CentOS Linux 7.2.1511

3) Sample source code or steps to reproduce

Not really sure if this is an issue. It's more likely to be me just missing something obvious. I'm using the following to send an email to a mailing list. The mailing list has over 2,000 members.

> var api_key = 'MyAPIKey';
> var domain = 'domain.com';
> var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});
> var htmlToText = require('html-to-text');
> var html = '`<p>My message.</p>`';
> var mailOptions = {
> 'from': 'Me <`noreply@domain.com`>',
> 'to': '`mailing-list@domain.com`',
> 'subject': 'Super Message',
> 'text': htmlToText.fromString(html,{ingnoreHref:true,ignoreImage:true}),
> 'html': html,
> 'o:tracking-opens':trackopens,
> 'o:tracking-clicks':trackclicks
> };
> mailgun.messages().send(mailOptions, function (sendError, body) {
> if (sendError) {return console.log(sendError);}
> return console.log(body);
> });

I'm getting an error: "Error: Too many recipients, max is 1000" from mailgun-js 'request.js' at line 309.

This makes it seem that I'm trying to send a batch email? But I'm not. Or - more likely - I thought I wasn't. The 'to' field is a mailing list that is on Mailgun. Yes, this mailing list contains more than 1000 addresses, but surely that's the point of the mailing list.

This is confusing me. Is there some mistake I'm making trying to send to a mailing list? 

Do you know where I'm going wrong?

**Comment by bojand** [comment]
Hello,
This is weird. Can you please check and see if you get the same error by doing a curl command to the Maingun API? Thanks.

**Comment by lunedam-git** [comment]
Hi,

I used:

>curl -s --user 'api:MyAPIKey' https://api.mailgun.net/v3/domain.com/messages -F from='Me <noreply@domain.com>' -F to=mailing-list@domain.com -F subject='Test' --form-string html='```<p>Test Message</p>```' -F text='Test Message' -F o:tracking-opens='true' -F o:tracking-clicks='true' -F o:testmode='true'

I had to use test mode to avoid blasting the mailing list members with unwanted test messages. This returned the message "Queued. Thank you." in the response JSON and I can see in the Mailgun logs all the test messages have been delivered.

I'm pretty sure that everything is being sent, I was just surprised to see that error popping up in my Node app log file the other day. I can't see anything in the Mailgun logs to indicate that there have been any delivery refusals or rejections to do with recipient numbers.

Regards.

**Comment by suriyaJaay** [comment]
hi,
can anyone answer for the following queries please? 

1.snippet for sending mails to mail list with node.js, html front end? 
2. how to show existing mail list from mailgun into html page.?

kindly do response. i'l share my snippet what i did so far..!!!

Thank you guys
