### ISSUE TITLE
Attaching data to emails

### ISSUE THREAD

**Issue by jluchiji** [bojand/mailgun-js#99]
Is it possible to attach data to emails as described [here](https://documentation.mailgun.com/user_manual.html#attaching-data-to-messages)?

**Comment by bojand** [comment]
Yes Just add it to the data...

```
var data = {
  from: 'Excited User <me@samples.mailgun.org>',
  to: 'serobnic@mail.ru',
  subject: 'Hello',
  text: 'Testing some Mailgun awesomness!',
  'v:whatever': 123,
  'v:test': true,
  'v:my-custom-data': {whatever: 123, test: true}
};

mailgun.messages().send(data, function (error, body) {
  console.log(body);
});
```

Those will be added to message header:

```
X-Mailgun-Variables: {"test": "true", "my-custom-data":
 "{\"whatever\":123,\"test\":true}", "whatever": "123"}
```

**Comment by blandman** [comment]
I am trying this now with no luck, X-Mailgun-Variables not present in any reply emails.

**Comment by zdraganov** [comment]
Not working here as well. Maybe API change from Mailgun?

**Comment by jorenbroekema** [comment]
Ye this library isn't really up to date, what the library should do is read 'h:X-MailgunVariables' property and stringify it for you :)

The author has said it's in maintenance mode but that he's willing to look at Pull Requests to add this.
